title: Dataworkz
email: pieter@dataworkz.nl
description: 'Corporate website'
url: 'https://dataworkz-nl.github.io/dataworkz-site/'
github_username: Dataworkz-NL
future: true

permalink: /news/:year/:month/:day/:title/

plugins:
  - jekyll-redirect-from

exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
