title: Dataworkz
email: pieter@dataworkz.nl
description: 'Corporate website'
github_username: Dataworkz-NL
future: true
layout: dataworkz


permalink: /news/:year/:month/:day/:title/

plugins:
  - jekyll-redirect-from

collections:
  - team

defaults:
  - scope:
      path: "images/technologies"
    values:
      techimage: true

exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
